blog/main/blog/urls.py
from . import views
from django.urls import path
from django.views.generic import RedirectView


app_name="blogs"
urlpatterns = [
    path('', views.index, name="index"),
    path('<str:slug>/', views.blog_post, name="blog_post")
]

blog/main/main/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('blog/', include('blog.urls')),
    path('admin/', admin.site.urls),
]

blog/main/blog/models.py
from django.db import models
from datetime import date

# Create your models here.
class Post(models.Model):
    id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(unique=True)
    author = models.CharField(max_length=100)
    date = models.DateField(default=date.today)
    content = models.TextField()

    class Meta:
        ordering = ['-date']

    def __str__(self):
        return self.title

blog/main/blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from .models import Post

def index(request):
    blogs = Post.objects.all()
    context = {'blogs': blogs}
    return render(request, 'blog/index.html', context=context)

def blog_post(request, slug):
    post = get_object_or_404(Post, slug=slug)
    context = {'post': post}
    return render(request, 'blog/post.html', context=context)

blog/main/blog/templates/base.html
<html>
{% load static %}
<link rel="stylesheet" href="{% static 'blog/style.css' %}" type="text/css" />

{% block header %}
<h1><a href="{% url 'blogs:index' %}">Nathan Woodruff</a></h1>
{% endblock %}

<section class="text">
{% block content %}
{% endblock %}
</section>

{% block footer %}
<section class="footer">
    <p>
        Developed by 
            <a href="https://github.com/nwoodr94" target="_blank" rel="noopener noreferrer">
            Nathan Woodruff
            </a> 
            <span role="img" aria-label="us flag"></span>
    </p>
</section>
{% endblock %}
</html>

blog/main/blog/templates/blog/index.html
{% extends "base.html" %}

{% block content %}
    <p class="welcome">
        Welcome to my blog, a place where I post things.
    </p>
    <br />
    <br />

    {%for blog in blogs%}
        <li><a href="{% url 'blogs:blog_post' slug=blog.slug %}">{{blog.title}}</a></li>
    {%endfor%}

{% endblock %}

blog/main/blog/templates/blog/post.html
{% extends "base.html" %}

{% block content %}
<section class="details">
<p>{{post.title}}</p>
<p>{{post.author}}</p>
<p>{{post.date}}</p>
</section>
<br />
<section class="post">
{{post.content|safe}}
</section>
{% endblock %}